### ISSUE TITLE
Cannot access phpBB-SEO ACP after migration to V3.1.0 - acp_gym_sitemaps

### ISSUE THREAD

**Issue by hbcafe** [phpBBSEO/usu#64]
To reproduce:
1. Start with an existing phpBB 3.0.12 database with phpBB-SEO premod
2. Install phpBB 3.1.0 in fresh directory
3. Copy config.php from previous version
4. Run database_update.php to migrate database from V3.0.12 to V3.1.0
5. Install phpBB-SEO usu & nodupe in ext/phpbbbseo from github
6. Access ACP and turn to PHPBB-SEO
7. Trigger error below is shown.

WORKAROUND:

Manually remove the phpBB-SEO related modules from PHPBB_MODULES table (4 rows). Clear cache and try again.
# 

Cannot find module ./../includes/acp/acp_gym_sitemaps.php

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/includes/functions_module.php
LINE: 571
CALL: trigger_error()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()
